[build-system]
requires = [ "setuptools", "setuptools_scm" ]
build-backend = "setuptools.build_meta"

[project]
name = "ts-criopy"
description = "LSST cRIO utilities."
license = { text = "GPL" }
classifiers = [ "Programming Language :: Python :: 3" ]
urls = { documentation = "https://ts-criopy.lsst.io", repository = "https://github.com/lsst-ts/ts_criopy" }
dynamic = [ "version" ]
dependencies = [
  "astropy",
  "numpy",
  "pandas",
  "pyside6",
  "pyyaml",
  "qasync",
  "moto",
  "boto3",
  "click",
  "jsonschema",
  "h5py",
  "ts_idl",
  "ts_salobj",
  "ts_xml",
  "ts_utils",
  "lsst_efd_client",
]

[project.scripts]
m1m3-bump-tests-times = "lsst.ts.criopy.m1m3_bump_tests_times:run"
M1M3GUI = "lsst.ts.criopy.m1m3gui:run"
M1M3SIMGUI = "lsst.ts.criopy.m1m3simgui:run"
M1M3TSGUI = "lsst.ts.criopy.m1m3tsgui:run"
VMSGUI = "lsst.ts.criopy.vmsgui:run"
VMSlogger = "lsst.ts.criopy.vmslogger:run"
vms5plot = "lsst.ts.criopy.vms5plot:run"

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }

[tool.setuptools.packages.find]
where = [ "python" ]

[tool.setuptools_scm]
write_to = "python/lsst/ts/criopy/version.py"
write_to_template = """
# Generated by setuptools_scm
__all__ = ["__version__"]
__version__ = "{version}"
"""

[tool.pytest.ini_options]
asyncio_mode = "auto"

[project.optional-dependencies]
dev = ["documenteer[pipelines]"]
