import setuptools

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""


setuptools.setup(
    name="ts_criopy",
    description="GUIs, Python packages and utilities for NI cRIO.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    use_scm_version={
        "write_to": "python/lsst/ts/cRIOpy/version.py",
        "write_to_template": scm_version_template,
    },
    package_dir={"": "python"},
    packages=setuptools.find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=["bin/M1M3GUI", "bin/M1M3TSGUI", "bin/VMSGUI", "bin/VMSlogger"],
    license="GPL3",
    project_urls={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/ts_cRIOpy",
    },
)
