#!/bin/bash
/usr/bin/docker run --rm --name $1 -v /vms-data/:/vms-data/:rw --network host vmslogger VMSlogger -5 --workdir /vms-data --template '${name}/%Y/%m/%d/${name}-%Y-%m-%dT%H:%M.${ext}' --rotate 1D M1M3 M2 Rotator
