{% set data = load_setup_py_data() %}

package:
  name: ts-criopy
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - M1M3GUI = lsst.ts.cRIO.M1M3GUI:run
    - M1M3TSGUI = lsst.ts.cRIOpy.M1M3TSGUI:run
    - VMSGUI = lsst.ts.cRIOpy.VMSGUI:run
    - VMSlogger = lsst.ts.cRIOpy.VMSlogger:run

test:
  requires:
    - ts-conda-build =0.3
    - numpy
    - pyside2
    - asyncqt
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
  commands:
    - pytest

requirements:
  host:
    - numpy
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - numpy
    - astropy
    - h5py
    - setuptools
    - setuptools_scm
    - pyside2
    - asyncqt
    - ts-idl
    - ts-salobj
