{% set data = load_setup_py_data() %}

package:
  name: ts-criopy
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - M1M3GUI = lsst.ts.criopy.M1M3GUI:run
    - M1M3TSGUI = lsst.ts.criopy.M1M3TSGUI:run
    - VMSGUI = lsst.ts.criopy.VMSGUI:run
    - VMSlogger = lsst.ts.criopy.VMSlogger:run

test:
  requires:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - ts-conda-build =0.3
    - numpy
    - pyside2
    - qasync
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - bin
    - tests
  commands:
    - pytest

requirements:
  build:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - numpy
    - python
    - pip
    - setuptools_scm
    - setuptools
    - xorg-libxfixes # [linux]
  run:
    - python
    - numpy
    - astropy
    - h5py
    - setuptools
    - setuptools_scm
    - pyside2
    - qasync
    - ts-idl
    - ts-salobj
